import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ajay Mathur
 */

public class dash3 extends javax.swing.JFrame {
public static String not;
    /**
     * Creates new form dash3
     */
    public dash3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        s3 = new javax.swing.JRadioButton();
        t3 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        s1 = new javax.swing.JRadioButton();
        t1 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        del = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        s2 = new javax.swing.JRadioButton();
        t2 = new javax.swing.JRadioButton();
        pas = new javax.swing.JTextField();
        ad = new javax.swing.JTextField();
        su = new javax.swing.JTextField();
        con = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        cl = new javax.swing.JTextField();
        srn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        buttonGroup1.add(s3);
        s3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        s3.setText("STUDENT");

        buttonGroup1.add(t3);
        t3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        t3.setText("TEACHER");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(s3)
                .addGap(18, 18, 18)
                .addComponent(t3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s3)
                    .addComponent(t3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(1570, 130, 290, 50);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("PROFESSION");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(1420, 140, 150, 30);

        buttonGroup1.add(s1);
        s1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        s1.setText("STUDENT");

        buttonGroup1.add(t1);
        t1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        t1.setText("TEACHER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(s1)
                .addGap(18, 18, 18)
                .addComponent(t1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1)
                    .addComponent(t1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(320, 80, 290, 50);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("PROFESSION");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(130, 90, 150, 30);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton8.setText("REMOVE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(1580, 290, 123, 60);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(320, 170, 160, 37);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton6.setText("LOGOUT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(810, 870, 169, 60);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(1020, 870, 107, 60);

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        jLabel16.setText("ADMIN ACCESS");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(670, 0, 360, 60);

        del.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(del);
        del.setBounds(1550, 210, 290, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("SR. NO.");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(1420, 210, 83, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton3.setText("ADD DATA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(970, 530, 203, 60);

        buttonGroup1.add(s2);
        s2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        s2.setText("STUDENT");

        buttonGroup1.add(t2);
        t2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        t2.setText("TEACHER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(s2)
                .addGap(18, 18, 18)
                .addComponent(t2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s2)
                    .addComponent(t2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(1040, 90, 290, 50);

        pas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(pas);
        pas.setBounds(1050, 450, 180, 40);

        ad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(ad);
        ad.setBounds(1050, 400, 180, 40);

        su.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(su);
        su.setBounds(1050, 300, 180, 35);

        con.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(con);
        con.setBounds(1050, 350, 180, 40);

        name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(name);
        name.setBounds(1050, 200, 180, 35);

        cl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(cl);
        cl.setBounds(1050, 250, 180, 35);

        srn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        srn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srnActionPerformed(evt);
            }
        });
        jPanel1.add(srn);
        srn.setBounds(1050, 150, 180, 35);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("PROFESSION");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(880, 100, 150, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("PASSWORD");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(910, 460, 140, 29);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("ADDRESS");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(920, 400, 100, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("CONTACT");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(910, 350, 110, 29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("SUBJECT");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(910, 300, 110, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("SR NO.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(920, 150, 76, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("NAME");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(930, 200, 80, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("CLASS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(930, 230, 80, 50);

        tb1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "SR NO.", "NAME", "CLASS", "SUBJECT", "CONTACT", "ADDRESS", "PASSWORD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(90, 230, 630, 700);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("VIEW DATABASE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 30, 269, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("UPDATE DATABASE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1240, 10, 314, 60);

        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(1300, 620, 590, 240);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("WRITE A NOTICE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1470, 530, 277, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1540, 890, 159, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ADMIN DB.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 2400, 1200);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("PROFESSION");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(130, 90, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1918, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1201, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srnActionPerformed
  // TODO add your handling code here:
    }//GEN-LAST:event_srnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


        
        DefaultTableModel model =(DefaultTableModel) tb1.getModel();
model.setRowCount(0);
if(s1.isSelected()==true){
        try{
        Class.forName("java.sql.DriverManager");
        Connection con=(Connection) 
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/sms","root","ajay");
        Statement stmt=(Statement) con.createStatement();
        String q = "SELECT * FROM sdb;";
        ResultSet rs= stmt.executeQuery(q);
        while(rs.next()) {
            int sr=rs.getInt("sr");
        String na= rs.getString("name");
         String cl= rs.getString("class");
         String sub= rs.getString("subject");
         int cont=rs.getInt("contact");
          String add= rs.getString("address");
          String pass= rs.getString("password");
          model.addRow(new Object[]{sr,na,cl,sub,cont,add,pass});
        
        }
    rs.close();
    stmt.close();
    con.close();
    }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
    
    }    }  
else
    if(t1.isSelected()==true){
        try{
        Class.forName("java.sql.DriverManager");
        Connection con=(Connection) 
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/sms","root","ajay");
        Statement stmt=(Statement) con.createStatement();
        String q = "SELECT * FROM tdb;";
        ResultSet rs= stmt.executeQuery(q);
        while(rs.next()) {
            int sr=rs.getInt("sr");
        String na= rs.getString("name");
         String cl= rs.getString("class");
         String sub= rs.getString("subject");
         int cont=rs.getInt("contact");
          String add= rs.getString("address");
          String pass= rs.getString("password");
          model.addRow(new Object[]{sr,na,cl,sub,cont,add,pass});
        
        }
    rs.close();
    stmt.close();
    con.close();
    }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
    
    }    }  

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
not=ta1.getText();     
JOptionPane.showMessageDialog(null, "notice forwards");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
LOGIN H= new LOGIN();
H.setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
int u=Integer.parseInt(del.getText());
        if(s3.isSelected()==true)
        {try{
        Class.forName("java.sql.DriverManager");
        Connection con= (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/sms","root","ajay");
        Statement stmt=(Statement)con.createStatement();
        
        stmt.executeUpdate("DELETE FROM sdb WHERE sr ='"+u+"';");
        {
        
   JOptionPane.showMessageDialog(null, "data deleted");
        }
    
    stmt.close();
    con.close();
    }
        catch(Exception e){JOptionPane.showMessageDialog(null, e);  
    
    }   }
        else
            
            if(t3.isSelected()==true)
 {
     try{
        Class.forName("java.sql.DriverManager");
        Connection con= (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/sms","root","ajay");
        Statement stmt=(Statement)con.createStatement();
       
        stmt.executeUpdate("DELETE FROM tdb WHERE sr ='"+u+"';");
        {
        
   JOptionPane.showMessageDialog(null, "data deleted");
        }
    
    stmt.close();
    con.close();
    }
        catch(Exception e){JOptionPane.showMessageDialog(null, e);  
    
    }   }// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 int sr=Integer.parseInt(srn.getText());
try {
  int rpn=Integer.parseInt(srn.getText());
     
}
catch (NumberFormatException e) {
     JOptionPane.showMessageDialog(null, e); //Not an integer
} 

String na=name.getText();
        int clas=Integer.parseInt(cl.getText());
        String cla=cl.getText();
        String sub=su.getText();
        int cont=Integer.parseInt(con.getText());
         String add=ad.getText();
          String pass=pas.getText();
        
        
        if(s2.isSelected()==true)
            
        {try{
        Class.forName("java.sql.DriverManager");
        Connection con= (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/sms","root","ajay");
        Statement stmt=(Statement)con.createStatement();
        
        stmt.executeUpdate("INSERT INTO sdb VALUES ('"+sr+"','"+na+"','"+clas+"','"+sub+"','"+cont+"','"+add+"','"+pass+"');");
        {
        
   JOptionPane.showMessageDialog(null, "data added");
        }
    
    stmt.close();
    con.close();
    }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);  
    
    }   }
        else
            if(t2.isSelected()==true)
 {try{
        Class.forName("java.sql.DriverManager");
        Connection con= (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/sms","root","ajay");
        Statement stmt=(Statement)con.createStatement();
        
         stmt.executeUpdate("INSERT INTO tdb VALUES ('"+sr+"','"+na+"','"+cla+"','"+sub+"','"+cont+"','"+add+"','"+pass+"');");
        {
        
   JOptionPane.showMessageDialog(null, "data added");
        }
    
    stmt.close();
    con.close();
    }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e);  
    
    }   }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dash3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dash3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dash3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dash3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dash3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cl;
    private javax.swing.JTextField con;
    private javax.swing.JTextField del;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pas;
    private javax.swing.JRadioButton s1;
    private javax.swing.JRadioButton s2;
    private javax.swing.JRadioButton s3;
    private javax.swing.JTextField srn;
    private javax.swing.JTextField su;
    private javax.swing.JRadioButton t1;
    private javax.swing.JRadioButton t2;
    private javax.swing.JRadioButton t3;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
