
import javax.swing.JOptionPane;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ajay Mathur
 */
public class LOGIN extends javax.swing.JFrame {
public static int sr;
    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        p1 = new javax.swing.JPasswordField();
        t1 = new javax.swing.JTextField();
        cb = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(610, 570, 159, 70);

        p1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel1.add(p1);
        p1.setBounds(700, 462, 200, 50);

        t1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel1.add(t1);
        t1.setBounds(700, 380, 200, 50);

        cb.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TEACHER", "STUDENT", "ADMIN" }));
        jPanel1.add(cb);
        cb.setBounds(690, 290, 209, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("PASSWORD");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(410, 470, 185, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("USER NAME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 390, 191, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("LOGIN AS ");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(400, 300, 168, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("LOGIN");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(600, 170, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGIN.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1500, 900);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String c= (String)cb.getSelectedItem();  
String pwd =new String(p1.getPassword());
String u= t1.getText();

if(c.equals("ADMIN")){ 
    if((u.equals("ajay"))&&(pwd.equals("ajay")))
    {
    dash3 H = new dash3();
H.setVisible(true);
dispose();


}
else
   JOptionPane.showMessageDialog(null, "Invalid user name or password");     }
else
    if(c.equals("TEACHER")){
    try{
        Class.forName("java.sql.DriverManager");
        Connection con= (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/sms","root","ajay");
        Statement stmt=(Statement)con.createStatement();
        String q = "SELECT * FROM tdb WHERE sr ='"+u+"';";
        ResultSet rs= stmt.executeQuery(q);
        while(rs.next()){
        String a= rs.getString("password");
        
        if((pwd.equals(a)))
    {
    DASH1 H = new DASH1();
H.setVisible(true);
dispose();


}
else
   JOptionPane.showMessageDialog(null, "Invalid user name or password");
        }
    rs.close();
    stmt.close();
    con.close();
    }
        catch(Exception e){JOptionPane.showMessageDialog(null, "error");  
    
    }
    
    }
else
    if(c.equals("STUDENT")){
    try{
        Class.forName("java.sql.DriverManager");
        Connection con= (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/sms","root","ajay");
        Statement stmt=(Statement)con.createStatement();
        String q = "SELECT * FROM sdb WHERE sr ='"+u+"';";
        ResultSet rs= stmt.executeQuery(q);
        while(rs.next()){
        String a= rs.getString("password");
        
        if((pwd.equals(a)))
    {
    dash2 H = new dash2();
H.setVisible(true);
dispose();
sr=Integer.parseInt(u);


}
else
   JOptionPane.showMessageDialog(null, "Invalid user name or password");
        }
    rs.close();
    stmt.close();
    con.close();
    }
        catch(Exception e){JOptionPane.showMessageDialog(null, "error");  
    
    }
    
    }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
